## Pandas

### Pandas Fundamentals

In [1]:
import pandas as pd
df=pd.read_csv("D:/MLAI/csv/earthquake.csv")
df

      focal_depth  latitude  longitude  richter
0              33    -52.26      28.30      6.7
1              36     45.53     150.93      5.8
2              57     41.85     142.78      5.8
3              67     29.19     141.15      6.2
4              30    -21.66     169.81      6.0
...           ...       ...        ...      ...
2173           13     51.54    -173.11      5.8
2174           97    -10.16     161.01      5.9
2175          527     27.87     139.51      5.8
2176           51     36.43     140.98      6.0
2177           41     24.02     122.23      5.8

[2178 rows x 4 columns]

In [ ]:
print(df.loc[0]) # get the values and column names for the first values

focal_depth    33.00
latitude      -52.26
longitude      28.30
richter         6.70
Name: 0, dtype: float64

In [ ]:
df.loc[[0, 1]] # getting the values of 2 rows

   focal_depth  latitude  longitude  richter
0           33    -52.26      28.30      6.7
1           36     45.53     150.93      5.8

In [ ]:
h = df.head()  # top 5 results -> head(10) : top 10 results
t = df.tail()  # bottom 5 results -> head(10) : bottom 10 results
h, t

(   focal_depth  latitude  longitude  richter
 0           33    -52.26      28.30      6.7
 1           36     45.53     150.93      5.8
 2           57     41.85     142.78      5.8
 3           67     29.19     141.15      6.2
 4           30    -21.66     169.81      6.0,
       focal_depth  latitude  longitude  richter
 2173           13     51.54    -173.11      5.8
 2174           97    -10.16     161.01      5.9
 2175          527     27.87     139.51      5.8
 2176           51     36.43     140.98      6.0
 2177           41     24.02     122.23      5.8)

In [ ]:
df.info() # information about the dataset

<class 'pandas.DataFrame'>
RangeIndex: 2178 entries, 0 to 2177
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   focal_depth  2178 non-null   int64
 1   latitude     2178 non-null   float64
 2   longitude    2178 non-null   float64
 3   richter      2178 non-null   float64
dtypes: float64(3), int64(1)
memory usage: 68.2 KB

## Data cleaning

In [ ]:
df = pd.read_csv("D:\MLAI\csv\data.csv")
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [ ]:
# use dropna(inplac=True) to replace the new content to the original file. dropna() removes all row containing NULL values
new_df = df.dropna()
new_df.info()

<class 'pandas.DataFrame'>
Index: 164 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  164 non-null    int64
 1   Pulse     164 non-null    int64
 2   Maxpulse  164 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.4 KB

In [ ]:
df.fillna(10, inplace=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  169 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

#### Replace only for specified column

In [10]:
# replaces NULL values of Calories column to "130"
df.fillna({"Calories": 130}, inplace=True)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
# Replacing with mean, median & mode
# x = df["Calories"].mean()
# x = df["Calories"].median()
x = df["Calories"].mode()[0]
df.fillna({"Calories": x}, inplace=True)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
# Wrong Format Data
# df["Date"] = pd.to_datetime(df["Date"], format="mixed")
# print(df.to_string())

In [ ]:
df.duplicated()
df.drop_duplicates(inplace=True)